import '../styles/globals.css';
import Nav from './components/nav';
import Footer from './components/footer';
import { interTight } from './fonts';


import { ThemeProvider } from 'next-themes';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${interTight.variable}`}>
    <body className=" text-[#030503]">
      <ThemeProvider enableSystem={true} defaultTheme="system">
        <Nav />
        {children}
        <Footer />
      </ThemeProvider>
    </body>
  </html>
  );
}
