import '../styles/globals.css';
import Nav from './components/nav';
import Footer from './components/footer';
import LoaderWrapper from './components/LoaderWrapper';
import { ThemeProvider } from 'next-themes';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="font-serif bg-gradient-to-t from-[#1D0D41] to-[#010001] ">
      <ThemeProvider enableSystem={true} defaultTheme="system">
        <LoaderWrapper>
          <Nav />
          {children}
          <Footer></Footer>
        </LoaderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
